[package]
name = "mini-ode"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
tch = "0.24.0"
anyhow = "1.0.103"
tracing = { version = "0.1.44", optional = true }

[features]
default = []
doc = ["tch/doc-only"]
warnings = ["dep:tracing"]

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["doc"]
